
#server.port=9000
#server.servlet.context-path=/boot06
server:
  port: 9000
  servlet:
    context-path: /boot06 

#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
